name: neom_video_editor
description: Video Editor Functionalities for Open Neom.
version: 1.2.0
homepage: https://github.com/Cyberneom/neom_video_editor
publish_to: 'none'

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  neom_core:
    git:
      url: git@github.com:Cyberneom/neom_core.git
  neom_commons:
    git:
      url: git@github.com:Cyberneom/neom_commons.git

  fraction: ^5.0.5
  video_editor: ^3.0.0
  easy_video_editor: ^0.1.2

  video_compress: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
